### ISSUE TITLE
Show Country-Specific Individual Browser Usage

### ISSUE THREAD

**Issue by fabb** [browserslist/browsersl.ist#109]
It‘s a bit confusing that when a country-specific query is made, the overall coverage at the bottom correctly shows the coverage in that country, but the individual browser usage percentages are always global.

e.g. `>0.1% in AT` shows browsers with an individual usage percentage of less than 0.1% because it‘s more in AT:
https://browserl.ist/?q=%3E0.1%25+in+AT

```
Firefox for Android 63 0.09%
Samsung Internet 6.2 0.01%
Samsung Internet 4 0.03%
Chrome 57 0.03%
Edge 15 0.03%
Firefox 61 0.07%
Firefox 60 0.08%
Opera 56 0%
Opera 55 0.06%
```

Since the website already recognizes when a country-specific query is made, and shows that in the overall sum, this could also automatically be done for individual browser usage percentages. Or alternatively something similar to caniuse.com could be used: show global numbers + numbers from a country the user can select.

**Comment by fabb** [comment]
Related: https://github.com/browserslist/browserslist/issues/324#issuecomment-443408317

**Comment by XhmikosR** [comment]
Is this still an issue?

**Comment by fabb** [comment]
Yes it is

**Comment by ezzatron** [comment]
Not stale, issue still exists.

**Comment by ai** [comment]
I will remove slate bot. This is good issue. We even should warn that some browser is not popular in global but extremely popular in done countries

**Comment by xyy94813** [comment]
Why i can't use country-specific query?
Is it supported before??

https://browsersl.ist/?q=%3E0.1%25+in+US

```
Error: Cannot Find Module 'Caniuse-Lite/Data/Regions/US.Js'
```

**Comment by ai** [comment]
We are planning to fix it during refactoring. Right now I am spending all my free time with PostCSS 8 release.

You can help us by spreading be about our fundraising on Open Collective. It will allow me to finish website refactoring sooner by using working hours.

**Comment by ai** [comment]
Done https://browsersl.ist/
