### ISSUE TITLE
Deploy with latest caniuse-db version?

### ISSUE THREAD

**Issue by Bouke** [browserslist/browsersl.ist#250]
I like this website, thank you for providing it!

The version of caniuse-db currently in use is 1.0.30001019, released Jan 5, 2020. Since that date Edge Blink has been released and various versions of Firefox and Chrome. As a result the versions shown here are outdated: https://browserl.ist. We just run into this as we advertise something like [last 2 Edge versions](https://browserl.ist/?q=last+2+Edge+versions). However as we've updated caniuse to some newer version, that doesn't mean Edge 17 and 18, but Edge 81 and 83.

**Comment by ai** [comment]
We are collecting funds for free big and important refactorings in Browserslist ecosystem including website.

https://opencollective.com/browserslist

**Comment by DamianOsipiuk** [comment]
For the time being you can use https://browserslist.innocore.pl/
It's automatically redeployed each week with latest caniuse version.
