### ISSUE TITLE
Page browsersl.ist is down, 404

### ISSUE THREAD

**Issue by tmbo** [browserslist/browsersl.ist#308]
[browsersl.ist/](https://browsersl.ist/) isn't reachable. I guess some recent change broke the deployment making the site unreachable.

**Comment by ai** [comment]
Yes, it could be Vercel deploy issue.

It is better to wait a new version rather than sending time of fixing old https://github.com/browserslist/browserl.ist/tree/v2

**Comment by igorlukanin** [comment]
I think this one is resolved 😄

**Comment by ai** [comment]
Yes, new version was deployed https://browsersl.ist/
