### ISSUE TITLE
List of small bugs/suggestions for MVP

### ISSUE THREAD

**Issue by a-chabin** [browserslist/browsersl.ist#310]
List of small errors and suggestions for MVP client and server

**Comment by a-chabin** [comment]
**[Server]**
Sort browser version keys by coverage

**Comment by a-chabin** [comment]
- [ ] [Client] Disable multi-columns on mobile screen
<img src="https://user-images.githubusercontent.com/22644149/182570200-06716db4-9805-4d47-b50e-7847a3f47451.png" alt="" width="200" />

**Comment by a-chabin** [comment]
- [ ] [Server] /api/social { githubStars: number, twitterFollowers: number } _not critical_
![image](https://user-images.githubusercontent.com/22644149/182570729-b514e871-0510-458f-b8e0-b61c56a8aab9.png)

**Comment by a-chabin** [comment]
- [ ] [Client] When clicking on the text, the placeholder does not click on the textarea

https://user-images.githubusercontent.com/22644149/182571422-3239c133-8bae-4d65-b9c2-fc7c3f1d3409.mov

_ Idea: `pointer-events: none` for caption, `pointer-events: all` for buttons_

**Comment by sashasushko** [comment]
![image](https://user-images.githubusercontent.com/4469056/182841722-4962dfcb-9f7e-4a1e-bac8-626ebf10aab1.png)

- [ ] Broken links
- [ ] Doubled Autoprefixer title in the get started block
- [ ] Extra space before comma

**Comment by sashasushko** [comment]
<img width="310" alt="Снимок экрана 2022-08-03 в 14 34 15" src="https://user-images.githubusercontent.com/4469056/182842432-d175e556-d1c6-40e6-8922-d68c3dab9fb6.png">
<img width="652" alt="Снимок экрана 2022-08-03 в 14 32 44" src="https://user-images.githubusercontent.com/4469056/182842467-d815fda4-5129-49b7-8e5c-52242b8a0185.png">

Links hover effect - scale - depends on link text width. It's ok for short texts (pic. 1) but looks strange in cases with long text (pic. 2).

**Comment by sashasushko** [comment]
<img width="623" alt="Снимок экрана 2022-08-04 в 18 14 53" src="https://user-images.githubusercontent.com/4469056/182844471-1ac7dde2-f4ac-418f-9222-689e6fb0483e.png">

- [ ] The query field is validated before the user input anything

**Comment by sashasushko** [comment]
<img width="617" alt="Снимок экрана 2022-08-04 в 18 17 57" src="https://user-images.githubusercontent.com/4469056/182845023-0320305e-a0b3-4146-ac9c-3b4ab361bb24.png">

- [ ] Links haven't line breaks

**Comment by sashasushko** [comment]
- [ ] Query form submitting not working in Firefox. The page just reloads.

**Comment by sashasushko** [comment]
<img width="1153" alt="Снимок экрана 2022-08-03 в 14 39 05" src="https://user-images.githubusercontent.com/4469056/182996141-c193581f-5833-48ac-b4bb-23c998169629.png">

- [ ] All `.Article` blocks have `overflow: scroll;` property. If the user turns on scrollbars visibility in macOS settings or the user is a Linux/Windows-user, scrollbars always show. It looks strange

**Comment by a-chabin** [comment]
- [ ] [Server] Errors due to rounding coverage values

- Query: `>0%`
- Region: Vanuatu

![image](https://user-images.githubusercontent.com/22644149/184059537-f85e11ab-b305-42da-bc1a-bc8ba7f6440f.png)

**Comment by a-chabin** [comment]
- [ ] [Client] Wrong region in `&region=` converts to `null` and interface not working
https://browserslist-demo.vercel.app/?q=defaults&region=wrong-name

**Comment by a-chabin** [comment]
- [ ] [Server] Errors due to rounding coverage values

Query: `>0%`
Region: `CH` (Switzerland)

https://browserslist-demo.vercel.app/?q=%3E0%25&region=CH
https://browserslist-demo.vercel.app/?q=since+0&region=VU
https://browserslist-demo.vercel.app/?q=%3E0%25&region=VA

![image](https://user-images.githubusercontent.com/22644149/184059537-f85e11ab-b305-42da-bc1a-bc8ba7f6440f.png)

**Comment by kseniiiiiiia** [comment]
- [ ] add mono-font to gray text
<img width="625" alt="Screenshot 2022-08-11 at 14 04 06" src="https://user-images.githubusercontent.com/104213162/184100344-1e5c7f40-e6d7-4762-8649-b7b7adc59568.png">

- [ ] Apply adaptive to errors
<img width="610" alt="Screenshot 2022-08-11 at 14 04 14" src="https://user-images.githubusercontent.com/104213162/184100644-c40539c6-e108-4e0c-a29d-8460ae87c12e.png">

- [ ] Add token colors to Github and check left margin (shoud be 6px) 
<img width="149" alt="Screenshot 2022-08-11 at 14 08 35" src="https://user-images.githubusercontent.com/104213162/184101210-4cbf46ff-e56e-40a8-9cab-dd5d2bc5e086.png">

- [ ] Move the underline 1px lower 
<img width="165" alt="Screenshot 2022-08-11 at 14 12 17" src="https://user-images.githubusercontent.com/104213162/184101602-01966cd5-6d19-4eaa-b7bb-4ec8a4349d75.png">

- [ ] Space between blocks should be 1px 
<img width="364" alt="Screenshot 2022-08-11 at 14 22 45" src="https://user-images.githubusercontent.com/104213162/184103220-4063e632-fde8-4e0d-8967-4cf1a2b016a6.png">

- [ ] Change the animation hover speed (from 0.3s to 0.2s) 

- [ ] Bug Safari: Blinking hover in links

**Comment by kseniiiiiiia** [comment]
- [ ] Add blue stroke while hovering + add round corners to fill 
<img width="358" alt="Screenshot 2022-08-12 at 12 13 14" src="https://user-images.githubusercontent.com/104213162/184313970-ff193db1-83f7-465a-b4a6-12ab6bab8385.png">

- [ ] Add a line "You can also check..." 
<img width="453" alt="Screenshot 2022-08-12 at 13 18 50" src="https://user-images.githubusercontent.com/104213162/184314198-80c35549-c071-42ff-a3df-9cd1212e4496.png">

- [ ] Check colors in blue buttons (looks brighter when designed)
- [ ] Check font size (looks bigger) 
<img width="491" alt="Screenshot 2022-08-12 at 12 37 21" src="https://user-images.githubusercontent.com/104213162/184314579-fd59f759-4508-441f-9ee1-fe2d6d21ea76.png">

**Comment by kseniiiiiiia** [comment]
- [ ] Maybe add a **standard** tooltip for hidden browsers?
![photo_2022-08-12 15 00 30](https://user-images.githubusercontent.com/104213162/184332854-906e38a9-0765-43b6-8fdf-b4628d15163a.jpeg)

**Comment by ai** [comment]
@kseniiiiiiia `Add a line "You can also check..."` was postponed

**Comment by sashasushko** [comment]
Now the documentation side scrolls as `<body/>` content and the table with results as a container with a `overflow: scroll` property.

Because of what scrollbars overlay each other (and in Linux and Windows they are generally visible both):
<img width="642" alt="Снимок экрана 2022-08-12 в 16 52 58" src="https://user-images.githubusercontent.com/4469056/184348726-78304635-4e8b-44aa-a64e-a86d765ca293.png">

This also leads to scrolling issue on mobile:
<img width="343" alt="Снимок экрана 2022-08-12 в 16 55 24" src="https://user-images.githubusercontent.com/4469056/184349231-f265eb7b-e486-4c35-a1e9-e6958ac8bd7d.png">

I propose: 
- remove scroll in the block with the table on mobile. Keep only the "natural scroll" on the `<body/>`
- remove scroll on the `<body/>` when data is in two cols. Keep only the block scrolls

<img width="1552" alt="Снимок экрана 2022-08-12 в 16 59 52" src="https://user-images.githubusercontent.com/4469056/184349743-161f3960-abab-4af8-9421-d565d93d47ce.png">

**Comment by kseniiiiiiia** [comment]
- [ ] Make heading 22
<img width="452" alt="Screenshot 2022-08-15 at 13 56 13" src="https://user-images.githubusercontent.com/104213162/184606476-8e926026-58d0-42dc-b46d-01241fb191de.png">

- [ ] Change color — background: rgba(63, 146, 255, 0.1);
<img width="621" alt="Screenshot 2022-08-15 at 13 57 14" src="https://user-images.githubusercontent.com/104213162/184606769-6b500398-90a8-4017-94fe-5353429aa1d2.png">

- [ ] Forgot outline
![photo_2022-08-15 14 00 28](https://user-images.githubusercontent.com/104213162/184607167-883ae729-a020-42f9-ae76-f2802bb82996.jpeg)
<img width="440" alt="Screenshot 2022-08-15 at 14 01 10" src="https://user-images.githubusercontent.com/104213162/184607183-c912ee49-df07-4909-a3d6-1e8057e4ccd2.png">

- [ ]  Change color to the upper step
<img width="579" alt="Screenshot 2022-08-15 at 14 02 45" src="https://user-images.githubusercontent.com/104213162/184607389-36138f52-27e2-4f3c-8474-8a7ae623f773.png">

**Comment by kseniiiiiiia** [comment]
- [ ] We forgot this blocks, aren't we?
<img width="544" alt="Screenshot 2022-08-15 at 15 31 53" src="https://user-images.githubusercontent.com/104213162/184620541-549ccdec-7c48-488d-92bb-49705471d0f3.png">

**Comment by ai** [comment]
I moved all unclosed bugs to separated issues. On current stage of the project it is better to handle them as separated issues,
