### ISSUE TITLE
Simplify CSS classes

### ISSUE THREAD

**Issue by ai** [browserslist/browsersl.ist#316]
Now we use this pattern for modifiers: `Block--mod` or `Block_element--mod`.

BEM uses this long classes for modifiers because in BEM you can add two blocks or elements on the single tag.

In our system, we can’t use two classes, so we do not need this long prefixes.

I suggest `.is-mod` pattern.

**Comment by ariarzer** [comment]
Deviation from the classical methodology complicates the contribution to the project.

Is it so important for as to do it?

**Comment by ai** [comment]
> Deviation from the classical methodology complicates the contribution to the project.

I don’t really believe in contributions from other people in projects like this.

Very likely that I will do all maintenance.

If I will be able to use the same methodology, which I have on all my other projects, it will simplify maintenance.

Also, we will have a small nice addition of having smaller HTML, JS, and CSS files 😸
