### ISSUE TITLE
A11y issues

### ISSUE THREAD

**Issue by ai** [browserslist/browsersl.ist#360]
Chrome Lighthouse shows many contrasts issues:

- [x] `add the Browserslist config to display compatible browsers`
- [x] `Supported by`
- [x] `Write the Browserslist config here`
- [x] Maybe `QueryLink`

Lack of description:
- [x] We need some `aria-label` or something to `<a>` in `Tweet`

**Comment by a-chabin** [comment]
From [AXE DevTools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd)


- [ ] Wrap all content to `<main>`
- [ ] Add `aria-label` to `<select>` without `<label>`


![image](https://user-images.githubusercontent.com/22644149/184348864-cdf06007-aa9c-447f-9f7b-ea48380bbc1a.png)
_The rest of the issues are already listed above by @ai ._
