### ISSUE TITLE
Allow to write multiline configs in form

### ISSUE THREAD

**Issue by ai** [browserslist/browsersl.ist#388]
Have no idea how to deal with it with our `press Enter to submit`. Maybe we should add auto-submit during the input?

**Comment by a-chabin** [comment]
Yes, I suggest making a demo. And add a little 300ms denounce for typing.

We need to see if users get annoyed by the error messages.

**Comment by igorlukanin** [comment]
I think we can do this:
* Enter to add a newline
* Cmd+Enter to submit
* Add gray-ish note like "Press ⌘+Enter" after "Display compatible browsers"

**Comment by ai** [comment]
And `Ctrl+Enter` for non-Mac users

**Comment by ai** [comment]
Copy-pasting of multi-line config doesn’t work too
