### ISSUE TITLE
Make clickable code snippets non-breakable

### ISSUE THREAD

**Issue by igorlukanin** [browserslist/browsersl.ist#395]
Right now, they might look strange with a line break.

<img width="689" alt="Screenshot 2022-08-14 at 23 49 58" src="https://user-images.githubusercontent.com/3852894/184552595-7f70950d-8ce8-45e2-ba91-b6aad14f1f82.png">

**Comment by a-chabin** [comment]
+1

But it may be worth correcting the content or breakpoints, otherwise not everything will fit.

![image](https://user-images.githubusercontent.com/22644149/184991489-ae58840d-959d-4df1-9589-a3caa47974b3.png)
