### ISSUE TITLE
Add styles to non-clickable <code>

### ISSUE THREAD

**Issue by igorlukanin** [browserslist/browsersl.ist#398]
Right now, only blue-ish links are properly rendered as code. Let's make sure we render regular code similar to blue-ish links (with border, distinct background and foreground — but different color, e.g., gray). See `or` and `,` here:

<img width="359" alt="Screenshot 2022-08-15 at 00 45 14" src="https://user-images.githubusercontent.com/3852894/184554287-2714fc15-18a1-43a0-8989-36765089b743.png">

Then, we can use this style for file names like here:

<img width="737" alt="Screenshot 2022-08-15 at 00 46 01" src="https://user-images.githubusercontent.com/3852894/184554294-477159f6-d140-445b-9f43-89d93e918de2.png">

**Comment by igorlukanin** [comment]
I also think we should reduce `<code>` font size a little bit to make look like it has the same vertical size as the regular text. Right now, `<code>` looks like it's one pixel more tall that the regulr text.

**Comment by ai** [comment]
> I also think we should reduce <code> font size a little bit to make look like it has the same vertical size as the regular text. Right now, <code> looks like it's one pixel taller than the regular text.

We use system font and do not sure about what fonts we use for regular and code cases

**Comment by ai** [comment]
> look similar to blue-ish links, just non-clickable

If elements looks the same, they should have the same behavior.

So I think we should not implement it.

**Comment by a-chabin** [comment]
Now I've done this as part of fonts PR #412 

![image](https://user-images.githubusercontent.com/22644149/184992150-1c75dad5-3711-4a6c-bc38-eb01c5b41a9f.png)

@ai 
@igorlukanin 

It seems good now
