### ISSUE TITLE
Make borders of `<select>` and `<textarea>` in browsers without CSS variables

### ISSUE THREAD

**Issue by a-chabin** [browserslist/browsersl.ist#401]
**Problem**
The site works good enough in old browsers. But the borders of `<textarea>` and `<select>` are not visible, which is quite critical.

**Motivation**
It seems that we should support at least QQ Browser and some versions of Opera mini with degradation, by default, since they are included in the selection `defaults and not support CSS variables`

My suggestions:
- Make a simple gray border / background fallback so as not to increase the CSS size and build time
- Add postcss to support CSS variables (it seems to be an overhead — we need to check how many KB we will add)

**QQ Browser 10.4**
<img width="200" alt="image" src="https://user-images.githubusercontent.com/22644149/184578861-e3d4dd48-23cc-4ed9-a1e9-0b903b7f2d27.png">

**defaults without supports css-variables**
![image](https://user-images.githubusercontent.com/22644149/184577425-e98fd9a8-a55a-475f-aa04-875f046c252d.png)

**Comment by a-chabin** [comment]
Another not critical problems with css variables in QQ browser 10.4

<img width="356" alt="image" src="https://user-images.githubusercontent.com/22644149/184583517-c14db5e0-358c-4b3d-a11f-4523a890791b.png">

**Comment by ai** [comment]
QQ is not really popular even in China, we are waiting to add it to `dead`.

**Comment by ai** [comment]
If the data is still readable, it is OK. We do not need 100% pixel perfect on all devices.
