### ISSUE TITLE
Apply styles to focused tweets

### ISSUE THREAD

**Issue by vitonsky** [browserslist/browsersl.ist#410]
When i focus on tweets, i see this

![image](https://user-images.githubusercontent.com/86191922/184681160-fbc0679b-eb2e-4932-b894-6e2405521858.png)

Let's change view for focus state on tweet. For example the same as while hover.

**Comment by pepelsbey** [comment]
The parent’s `overflow: hidden` is causing this.

https://user-images.githubusercontent.com/105274/184697030-88c68ae2-9753-4aa9-a2f2-264a618adc68.mov

**Comment by ai** [comment]
Seems like we need `border-radius` on link too
