### ISSUE TITLE
Audience coverage issues

### ISSUE THREAD

**Issue by ai** [browserslist/browsersl.ist#423]
On `>0%` I expect to have ≤ 100 % of audience coverage.

But often we have > 100%.

https://browsersl.ist/?q=%3E0%25+in+alt-an&region=alt-an

![Снимок экрана от 2022-08-17 02-18-52](https://user-images.githubusercontent.com/19343/185007039-a9a224f8-458b-4c5f-890b-9f7a54cc79ab.png)

Sometimes we have <100% but seems like because not all browsers are in Can I Use.

**Comment by a-chabin** [comment]
Another problem related to the choice of region — we output incorrect versions for query without `in`.

- [ ] Write test with `deepEqual`
- `await getBrowsers('>1%', 'alt-as', 'alt-as').browsers`
- `await getBrowsers('>1% in alt-as', 'alt-as').browsers`
- `await getBrowsers('>1% in alt-as', 'alt-ww').browsers` — Maybe. This is a frequent scenario, but we can do smart region recognition on the client.

## Errors with displayed versions

**https://browsersl.ist/?q=%3E1%25&region=alt-as** **(bug)**
<img src="https://user-images.githubusercontent.com/22644149/185062181-1195a397-a5cc-4989-a03a-d7fc70042b6f.png" width="400" />

**https://browsersl.ist/?q=%3E1%25+in+alt-as&region=alt-as** **(good)**
<img src="https://user-images.githubusercontent.com/22644149/185062164-f06de231-50d3-405f-9ed3-a071094b8f26.png" width="400" />

**https://browsersl.ist/?q=%3E1%25+in+alt-as** **(frequent scenario with bugs)**
<img src="https://user-images.githubusercontent.com/22644149/185062648-9b0cf58e-1e0d-4da6-8c07-7b8e17575172.png" width="400" />

**Comment by ai** [comment]
We did whatever we can on our side, so I am closing the issue
