### ISSUE TITLE
Add `,` and `#` support to multiline config

### ISSUE THREAD

**Issue by ai** [browserslist/browsersl.ist#433]
This config

```
> 1%,
last 2 versions
```

leads to `Unknown browser query ""`

https://browsersl.ist/?q=%3E+2%25%2C%2Clast+2+version

**Comment by a-chabin** [comment]
Now we have a temporary solution
https://github.com/browserslist/browsersl.ist/pull/435

The idea of the solution by @ai
https://github.com/browserslist/browsersl.ist/pull/435#issuecomment-1218990106

**Comment by ai** [comment]
@AleksandrSl no, it is not in a progress and PR is welcome
