### ISSUE TITLE
Website loops through all regions on its own

### ISSUE THREAD

**Issue by Haroenv** [browserslist/browsersl.ist#488]
I don't know what's causing this as the dev tools can't be opened when this is happening, but the region automatically updates, and it refreshes the page.

https://user-images.githubusercontent.com/6270048/210528300-4a166833-5add-40d2-8e35-1d99e703cd3c.mov

It doesn't happen in Chrome, but it does in Safari Tech Preview, Release 159 (Safari 16.4, WebKit 17615.1.12.130.1). I haven't yet tried other browsers

**Comment by ai** [comment]
1. Do you have it in stable version of Safari?
2. What do you have in console?
3. Does it have when you just open a page?

**Comment by Haroenv** [comment]
I did manage to load the console by opening it before loading browserslist and when pausing I'm in

```js
window.addEventListener("hashchange", () => {
    V()
});

// and then:

function V() {
    let e = new URLSearchParams(location.hash.slice(1)),
        t = e.get("q"),
        r = e.get("region");
    K({
        query: t,
        region: r
    }),
    h()
}
function h() {
    d.dispatchEvent(new Event("submit", {
        cancelable: !0
    }))
}
d.addEventListener("submit", e => {
    e.preventDefault();
    let t = new FormData(d),
        r = Ee(t.get("query")),
        n = t.get("region");
    qe(r, n),
    Ge(r, n),
    we(n)
});
function qe(e, t) {
    let r = new URLSearchParams;
    e && r.set("q", e),
    t && t !== R && r.set("region", t),
    location.hash = "#" + r
}
```

so I can see how that gets into an infinite loop, but not sure what causes it to start and to loop through the regions.

I can't reproduce it in stable Safari, Version 15.4 (17613.1.17.1.13).

I'll try updating to the latest tech preview and seeing if it still happens

**Comment by ai** [comment]
> I can't reproduce it in stable Safari, Version 15.4 (17613.1.17.1.13).

Could it be a bug of TP? Anyway it is a beta version.

**Comment by Haroenv** [comment]
Yes, that would probably be the case? I just updated to `Release 160 (Safari 16.4, WebKit 17615.1.14.3)` and it still happens. Feel free to close if nobody else can reproduce / elsewhere :)
