### ISSUE TITLE
Audience coverage is summing the results incorrectly

### ISSUE THREAD

**Issue by MonstraG** [browserslist/browsersl.ist#512]
Here is the result for the `cover: 80%` query:

<details>
<summary> screenshot </summary>

![image](https://github.com/browserslist/browsersl.ist/assets/17963791/7a1e6f09-ca50-4472-9115-1c1a32ed08f8)

</details>

`38.3 + 2.9 + 16.3 + 1.9 + 8.2 + 1.2 + 1.1 + 3.6 + 2.4 + 1.4 + 1.2 + 1.1 + 1.1` does in fact equal `80.7`, so it correctly covers 80%, but `Audience coverage` shows 73.7 for some reason 

UPD:

Here's the network response being made and info in `browsers` is correct and adds up to 80.5, but ` "coverage": 73.68` is wrong. That value is taken from `browserslist`:
[let coverage = roundNumber(browserslist.coverage(browsersByQuery, region))](https://github.com/browserslist/browsersl.ist/blob/3428b60466af2c0d72fbdbee4e970fb7281b3a00/server/lib/get-browsers.js#L77)

<details>
<summary>network response</summary>

```json
{
  "browsers": [
    {
      "coverage": 38.27,
      "id": "and_chr",
      "name": "Chrome for Android",
      "versions": {
        "115": 38.27
      }
    },
    {
      "coverage": 21.15,
      "id": "chrome",
      "name": "Chrome",
      "versions": {
        "109": 1.89,
        "114": 16.34,
        "115": 2.92
      }
    },
    {
      "coverage": 10.42,
      "id": "ios_saf",
      "name": "Safari on iOS",
      "versions": {
        "16.5": 8.21,
        "16.3": 1.16,
        "16.1": 1.05
      }
    },
    {
      "coverage": 3.57,
      "id": "edge",
      "name": "Edge",
      "versions": {
        "114": 3.57
      }
    },
    {
      "coverage": 2.36,
      "id": "safari",
      "name": "Safari",
      "versions": {
        "16.5": 2.36
      }
    },
    {
      "coverage": 1.38,
      "id": "firefox",
      "name": "Firefox",
      "versions": {
        "115": 1.38
      }
    },
    {
      "coverage": 1.23,
      "id": "samsung",
      "name": "Samsung Internet",
      "versions": {
        "21": 1.23
      }
    },
    {
      "coverage": 1.06,
      "id": "opera",
      "name": "Opera",
      "versions": {
        "99": 1.06
      }
    },
    {
      "coverage": 1.05,
      "id": "op_mini",
      "name": "Opera Mini",
      "versions": {
        "all": 1.05
      }
    }
  ],
  "config": "cover 80%",
  "coverage": 73.68,      <-- WRONG
  "lint": [
    ...
  ],
  "region": "alt-ww",
  "updated": 1692779145000,
  "versions": {
    "browserslist": "4.21.10",
    "caniuse": "1.0.30001522"
  }
}
```
</details>

so it seems that the problem is in `browserslist`, not website.

**Comment by MonstraG** [comment]
I tried
>npx browserslist --coverage "cover 80%"
These browsers account for 80.9% of all users globally

So browsers list does coverage correctly, so I'm not sure where the problem is now

**Comment by ai** [comment]
I am busy on another open source project. Can you do the investigation? I have no idea where to start too.

**Comment by ai** [comment]
> npx browserslist --coverage "cover 80%"

Be sure that website and CLI uses the same version of `caniuse-lite`. You can check it in the footer of right panel and in your npm’s lock file.

**Comment by MonstraG** [comment]
So, I made sure that on both `caniuse-lite` version is 1.0.30001523.

I changed `get-browsers.js` slightly:
```js
  let coverageRegion = roundNumber(browserslist.coverage(browsersByQuery, region))
  let coverageNoRegion = roundNumber(browserslist.coverage(browsersByQuery))
  console.log({region, coverageRegion, coverageNoRegion})
```
and that gave the following: `{ region: 'alt-ww', coverageRegion: 73.68, coverageNoRegion: 80.49 }`
(region variable is unchanged and by default has that value)

So the difference is down to the `region`.

**Comment by MonstraG** [comment]
I found commit where it broke - https://github.com/browserslist/browsersl.ist/commit/0ca3b90406b3e4f983a70bf3731adb96f6ae7e8a

**Comment by ai** [comment]
> region.json did not change in that commit, what?

`client/data/regions.json` has only region codes, not a population data.

We are taking statistics by that code in the server.

Could you compare website server’s code with CLI code? Maybe try to run both of them in Node.js REPL (you don’t need HTTP server to emulate server’s algorithm).

**Comment by MonstraG** [comment]
cloned `browserslist` itself, tried the following:
```
"caniuse-lite": "1.0.30001519",
> node ./cli.js --coverage=alt-ww "cover 80%"  
These browsers account for 73.68% of all users in the ALT-WW

"caniuse-lite": "1.0.30001520",
> node ./cli.js --coverage=alt-ww "cover 80%" 
These browsers account for 80.9% of all users in the ALT-WW
```

**Comment by MonstraG** [comment]
Hmm, caniuse-db gets updated somewhat regularly, while `alt-ww.json`  about once a month, with last being 2023-07-04, could it be that global data changed so much over couple of weeks?

**Comment by ai** [comment]
> caniuse-db gets updated somewhat regularly, while alt-ww.json about once a month, with last being 2023-07-04, could it be that global data changed so much over couple of weeks, and regional data is just old?

`caniuse-db`, to be honest, is very un-normalize and contains many unexpected results (20-30% o Browserslist is fixing `caniuse-db` normalization).

So, I am afraid, it could be a reason of issue.

Do you have in mind some hack to fix it on our side?

**Comment by MonstraG** [comment]
The only thing that I could think of right now is to just not pass `alt-ww` and use `undefined` as default, but that, of course, would not help with mismatches in other regions.

And if my assumptions about how `browserslist-lint` works are correct, this query will still fail linting.

**Comment by MonstraG** [comment]
I checked out original `data.json` file from `caniuse-db`, and it seems like that update adjusted a lot of the numbers:
chrome global usage before (30001519):
```
...
        "114": 14.553,
        "115": 0.021295,
        "116": 0.021295,
...
```

chrome global usage after (30001520):
```
...
        "114": 16.3375,
        "115": 2.92,
        "116": 0.021345,
...
```

that's where it's loosing 3%.

But regional data did not update, so it still says 114: 14.553, so the problem is in very source. 

I guess we can just wait until next regional data update in about 2 weeks going to resolve it

**Comment by ai** [comment]
Thanks for the research!

**Comment by a-chabin** [comment]
@MonstraG 

Thank you for your issue and research!
We fix it in https://github.com/browserslist/browsersl.ist/pull/513 (now we not using stats from `alt-ww.json`)
